top_hfsm_v2_node:
  ros__parameters:
    intent_cmd_topic: /hfsm/intent_commands
    intent_fb_topic: /hfsm/intent_feedback
    hfsm_update_period_ms: 20

    arm_action_name: move_arm
    arm_server_wait_ms: 100

    gripper_cmd_topic: /gripper_commands
    gripper_publish_period_ms: 20
