version: 1

AUTO_INIT:
  steps:
    - id: gripper_open
      kind: gripper.open

    - id: move_home_joints
      kind: arm.move_joints
      timeout_ms: 8000
      max_retries: 1
      params:
        target_joints:
          type: double_array
          preset: HOME
