version: 1

TEST_CARTESIAN:
  steps:
    - id: move_start_pose
      kind: arm.move_pose
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_pose:
          type: double_array
          preset: CARTESIAN_START_POSE

    - id: move_z_axis
      kind: arm.move_vector
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_vector:
          type: double_array
          preset: LINE_START_TO_Z_VECTOR
        target_length: 0.316108

    - id: move_y_axis
      kind: arm.move_vector
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_vector:
          type: double_array
          preset: LINE_Z_TO_Y_VECTOR
        target_length: 0.380275

    - id: move_x_axis
      kind: arm.move_vector
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_vector:
          type: double_array
          preset: LINE_Y_TO_X_VECTOR
        target_length: 0.237432

    - id: move_start_pose
      kind: arm.move_pose
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_pose:
          type: double_array
          preset: CARTESIAN_START_POSE

    - id: move_random
      kind: arm.move_vector
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_vector:
          type: double_array
          preset: LINE_START_TO_RANDOM_VECTOR
        target_length: 0.31752
