version: 1

TEST_CARTESIAN:
  steps:

    - id: move_home_joints
      kind: arm.move_joints
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_joints:
          type: double_array
          preset: HOME

    - id: move_z_axis
      kind: arm.move_vector
      timeout_ms: 80000
      max_retries: 1
      post_delay_ms: 1000
      params:
        target_vector:
          type: double_array
          preset: LINE_START_TO_Z_VECTOR
        target_length: 0.316108

    - id: move_home_joints
      kind: arm.move_joints
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_joints:
          type: double_array
          preset: HOME

    - id: move_y_axis
      kind: arm.move_vector
      timeout_ms: 80000
      max_retries: 1
      post_delay_ms: 1000
      params:
        target_vector:
          type: double_array
          preset: LINE_START_TO_Y_VECTOR
        target_length: 0.211458

    - id: move_home_joints
      kind: arm.move_joints
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_joints:
          type: double_array
          preset: HOME  

    - id: move_x_axis
      kind: arm.move_vector
      timeout_ms: 80000
      max_retries: 1
      post_delay_ms: 1000
      params:
        target_vector:
          type: double_array
          preset: LINE_START_TO_X_VECTOR
        target_length: 0.108122

    - id: move_home_joints
      kind: arm.move_joints
      timeout_ms: 8000
      max_retries: 1
      post_delay_ms: 200
      params:
        target_joints:
          type: double_array
          preset: HOME

    - id: move_random
      kind: arm.move_vector
      timeout_ms: 80000
      max_retries: 1
      post_delay_ms: 1000
      params:
        target_vector:
          type: double_array
          preset: LINE_START_TO_RANDOM_VECTOR
        target_length: 0.31752
