version: 1

TEST_SOLVE:
  steps:
    - id: move_normal_pose0
      kind: arm.move
      timeout_ms: 8000
      max_retries: 1
      params:
        target_pose: [-0.52816, 0.07035, 0.57682, -0.35088, -0.59813, 0.36457, 0.62146]

    - id: gripper_close
      kind: gripper.cmd
      post_delay_ms: 600
      params:
        action: close

    - id: move_cartesian_pose1
      kind: arm.move
      timeout_ms: 8000
      max_retries: 1
      params:
        target_vector: [-0.10315, -0.122381, 0.09803]

    - id: move_home_joints
      kind: arm.move
      timeout_ms: 8000
      max_retries: 1
      params:
        target_joints:
          type: double_array
          preset: HOME
