usb_cdc:
  ros__parameters:
    vendor_id: 0x0483
    product_id: 0x5740
    publish_period_ms: 10
    send_period_ms: 5
    servo_teleop_mode: false # 设置为 true 时，只发布 custom_joint_state；需同时启动 fake_system。
    debug_override_enabled: false
    debug_intent_id: 0
    startup_joint_targets: [0.0, -0.6109, -2.1293, 0.0, 0.0, 0.0]
    slot_state_topic: "/slot_states"
    slot_cmd_topic: "/slot_cmds"
